/*
 * INFO 5100 - Application Engineering and Development
 * Assignment 3 - Profiles and Work Areas
 * Dias Mukhametrakhim, NUID 003185578
 */

package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Profiles.EmployeeProfile;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Lists every employee (admin). From here the admin registers a new employee
 * or opens one to update or delete them.
 *
 * @author kal bugrara (skeleton), Dias Mukhametrakhim (Assignment 3)
 */
public class ManagePersonsJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    UserAccount currentUser;    // the admin who is logged in


    /**
     * @param bz the business that holds every directory
     * @param current the admin who is logged in (they may not delete their own employee profile)
     * @param jp the CardLayout panel that holds the screen stack
     */
    public ManagePersonsJPanel(Business bz, UserAccount current, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        currentUser = current;
        initComponents();
        refreshTable();
    }
    
    /** Reloads the table: one row per employee. */
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        model.setRowCount(0);

        for (EmployeeProfile ep : business.getEmployeeDirectory().getEmployeeList()) {
            UserAccount ua = business.getUserAccountDirectory().findByProfile(ep);
            Object[] row = new Object[6];
            row[0] = ep.getPerson().getPersonId();     // the NUID finds the employee again on selection
            row[1] = ep.getPerson().getName();
            row[2] = ep.getDepartment();
            row[3] = ep.getTitle();
            row[4] = ep.getPerson().getEmail();
            row[5] = ua == null ? "No account" : ua.getUserLoginName();
            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnRegister = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 58, 95));
        setLayout(null);

        btnBack.setBackground(new java.awt.Color(46, 134, 222));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 420, 72, 23);

        btnUpdate.setBackground(new java.awt.Color(46, 134, 222));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("View / Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(400, 420, 230, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Personnel (HR)");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUID", "Name", "Department", "Title", "Email", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblEmployees);
        if (tblEmployees.getColumnModel().getColumnCount() > 0) {
            tblEmployees.getColumnModel().getColumn(0).setResizable(false);
            tblEmployees.getColumnModel().getColumn(2).setResizable(false);
            tblEmployees.getColumnModel().getColumn(3).setResizable(false);
            tblEmployees.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 610, 270);

        btnRegister.setBackground(new java.awt.Color(0, 128, 0));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register Employee");
        btnRegister.setBorderPainted(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister);
        btnRegister.setBounds(190, 420, 150, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblEmployees.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select an employee first.",
                    "No employee selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String nuid = (String) tblEmployees.getValueAt(row, 0);
        EmployeeProfile employee = business.getEmployeeDirectory().findEmployee(nuid);
        AdministerPersonJPanel detail = new AdministerPersonJPanel(business, employee, currentUser, CardSequencePanel);
        CardSequencePanel.add("EmployeeDetail", detail);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        AdministerPersonJPanel detail = new AdministerPersonJPanel(business, null, currentUser, CardSequencePanel);
        CardSequencePanel.add("EmployeeDetail", detail);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

}
