/*
 * INFO 5100 - Application Engineering and Development
 * Assignment 3 - Profiles and Work Areas
 * Dias Mukhametrakhim, NUID 003185578
 */
package UserInterface.WorkAreas.AdminRole.ManageStudentsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import UserInterface.Validator.Validator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * One student profile. Opened with a student, the admin can update or delete
 * it; opened with null, it adds a new student by NUID. Adding a student does
 * not create a login: the student signs up with their NUID.
 *
 * @author Dias Mukhametrakhim
 */
public class AdministerStudentJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    StudentProfile student;     // null while adding a new student
    
    public AdministerStudentJPanel(Business bz, StudentProfile sp, JPanel jp) {
        CardSequencePanel = jp;
        business = bz;
        student = sp;
        initComponents();
        fieldAccount.setEditable(false);

        if (student == null) {
            lblTitle.setText("Add New Student");
            btnSave.setText("Add Student");
            btnDelete.setVisible(false);
            fieldAccount.setText("Not signed up");
        } else {
            btnSave.setText("Save Changes");
            fieldNuid.setEditable(false);
            showStudent();
        }
    }
    
        /** Fills the form from the selected student. */
    private void showStudent() {
        Person person = student.getPerson();
        lblTitle.setText("Student: " + person.getName());
        fieldNuid.setText(person.getPersonId());
        fieldName.setText(person.getName());
        fieldEmail.setText(person.getEmail());
        fieldPhone.setText(person.getPhone());
        fieldProgram.setText(student.getProgram());
        UserAccount ua = business.getUserAccountDirectory().findByProfile(student);
        fieldAccount.setText(ua == null ? "Not signed up" : ua.getUserLoginName());
    }

    /** The fields every student needs, checked top to bottom. */
    private boolean detailsAreFilled() {
        return Validator.isFilled(this, fieldNuid, "NUID")
                && Validator.isFilled(this, fieldName, "Name")
                && Validator.isFilled(this, fieldEmail, "Email")
                && Validator.isFilled(this, fieldPhone, "Phone")
                && Validator.isFilled(this, fieldProgram, "Program");
    }

    /** Copies the form into the person and the student profile. */
    private void copyDetailsInto(Person person, StudentProfile sp) {
        person.setName(fieldName.getText().trim());
        person.setEmail(fieldEmail.getText().trim());
        person.setPhone(fieldPhone.getText().trim());
        sp.setProgram(fieldProgram.getText().trim());
    }

    private void addStudent() {
        if (!detailsAreFilled()) {
            return;
        }
        String nuid = fieldNuid.getText().trim();
        if (business.getPersonDirectory().findPerson(nuid) != null) {
            JOptionPane.showMessageDialog(this, "NUID " + nuid + " is already registered.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Person person = business.getPersonDirectory().newPerson(nuid, fieldName.getText().trim());
        StudentProfile sp = business.getStudentDirectory().newStudentProfile(person);
        copyDetailsInto(person, sp);
        JOptionPane.showMessageDialog(this, "Student added. They can now sign up with NUID " + nuid + ".",
                "Student added", JOptionPane.INFORMATION_MESSAGE);
        goBack();
    }

    private void saveChanges() {
        if (!detailsAreFilled()) {
            return;
        }
        copyDetailsInto(student.getPerson(), student);
        showStudent();
        JOptionPane.showMessageDialog(this, "Student updated.", "Saved", JOptionPane.INFORMATION_MESSAGE);
    }

    /** Removes this screen and shows the student list again, reloaded. */
    private void goBack() {
        CardSequencePanel.remove(this);
        java.awt.Component[] stack = CardSequencePanel.getComponents();
        java.awt.Component below = stack[stack.length - 1];
        if (below instanceof ManageStudentsJPanel) {
            ((ManageStudentsJPanel) below).refreshTable();
        }
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblNUID = new javax.swing.JLabel();
        fieldNuid = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        lblProgram = new javax.swing.JLabel();
        fieldProgram = new javax.swing.JTextField();
        lblAccount = new javax.swing.JLabel();
        fieldAccount = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lblPhone = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Student");

        lblNUID.setText("NUID");

        lblName.setText("Name");

        lblEmail.setText("Email");

        lblProgram.setText("Program");

        lblAccount.setText("Account");

        btnDelete.setText("Delete Student");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblPhone.setText("Phone");

        fieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhoneActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblNUID))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblName))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnBack))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fieldAccount, fieldEmail, fieldName, fieldNuid, fieldPhone, fieldProgram});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProgram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccount)
                    .addComponent(fieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(32, 32, 32)
                    .addComponent(lblNUID)
                    .addGap(13, 13, 13)
                    .addComponent(lblName)
                    .addGap(13, 13, 13)
                    .addComponent(lblEmail)
                    .addGap(203, 203, 203)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDelete)
                        .addComponent(btnSave))
                    .addGap(57, 57, 57)
                    .addComponent(btnBack)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fieldAccount, fieldEmail, fieldName, fieldNuid, fieldPhone, fieldProgram});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        UserAccount ua = business.getUserAccountDirectory().findByProfile(student);
        String message = "Delete " + student.getPerson().getName() + "?"
                + (ua == null ? "" : " Their login \"" + ua.getUserLoginName() + "\" will be deleted too.");
        int answer = JOptionPane.showConfirmDialog(this, message, "Confirm delete",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (answer != JOptionPane.YES_OPTION) {
            return;
        }
        business.deleteProfile(student);
        JOptionPane.showMessageDialog(this, "Student deleted.", "Deleted", JOptionPane.INFORMATION_MESSAGE);
        goBack();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (student == null) {
            addStudent();
        } else {
            saveChanges();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAccount;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldNuid;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldProgram;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
