/*
 * INFO 5100 - Application Engineering and Development
 * Assignment 3 - Profiles and Work Areas
 * Dias Mukhametrakhim, NUID 003185578
 */
package UserInterface.WorkAreas.MyProfileWorkResp;

import Business.Person.Person;
import Business.Profiles.EmployeeProfile;
import Business.Profiles.FacultyProfile;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Shows the logged-in user their own profile and login details. The same
 * page serves admins, faculty and students; only the two role rows differ.
 *
 * @author Dias Mukhametrakhim
 */
public class MyProfileJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    UserAccount useraccount;    // the user who is logged in

    public MyProfileJPanel(UserAccount ua, JPanel jp) {
        useraccount = ua;
        CardSequencePanel = jp;
        initComponents();
        showProfile();
    }
    
    private void showProfile() {
        Profile profile = useraccount.getAssociatedPersonProfile();
        Person person = profile.getPerson();
        lblTitle.setText("My Profile - " + person.getName());
        fill(fieldRole, profile.getRole());
        fill(fieldName, person.getName());
        fill(fieldNuid, person.getPersonId());
        fill(fieldEmail, person.getEmail());
        fill(fieldPhone, person.getPhone());
        fill(fieldUsername, useraccount.getUserLoginName());
        fill(fieldLastLogin, useraccount.getLastAccessedText());
        fill(fieldLastUpdated, useraccount.getLastUpdatedText());

        // The two rows below depend on the role
        if (profile instanceof StudentProfile) {
            lblExtra1.setText("Program:");
            fill(fieldExtra1, ((StudentProfile) profile).getProgram());
            lblExtra2.setVisible(false);
            fieldExtra2.setVisible(false);
        } else if (profile instanceof EmployeeProfile) {
            lblExtra1.setText("Department:");
            fill(fieldExtra1, ((EmployeeProfile) profile).getDepartment());
            lblExtra2.setText("Title:");
            fill(fieldExtra2, ((EmployeeProfile) profile).getTitle());
        } else if (profile instanceof FacultyProfile) {
            lblExtra1.setText("Department:");
            fill(fieldExtra1, ((FacultyProfile) profile).getDepartment());
            lblExtra2.setText("Title:");
            fill(fieldExtra2, ((FacultyProfile) profile).getTitle());
        }
    }
    
        /** Puts a value in a read-only field, or "Not set" when there is none. */
    private void fill(JTextField field, String value) {
        field.setText(value == null || value.trim().isEmpty() ? "Not set" : value);
        field.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblNUID = new javax.swing.JLabel();
        fieldNuid = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        lblLastLogin = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        fieldRole = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        fieldExtra1 = new javax.swing.JTextField();
        fieldExtra2 = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblExtra1 = new javax.swing.JLabel();
        lblExtra2 = new javax.swing.JLabel();
        lblExtra3 = new javax.swing.JLabel();
        fieldLastLogin = new javax.swing.JTextField();
        lblAccountUpdated = new javax.swing.JLabel();
        fieldLastUpdated = new javax.swing.JTextField();

        setBackground(new java.awt.Color(31, 58, 95));

        btnBack.setBackground(new java.awt.Color(46, 134, 222));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("My Profile");

        lblNUID.setForeground(new java.awt.Color(255, 255, 255));
        lblNUID.setText("NUID");

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");

        lblLastLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLastLogin.setText("Last login");

        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Role");

        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");

        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Phone");

        lblExtra1.setForeground(new java.awt.Color(255, 255, 255));
        lblExtra1.setText("Department");

        lblExtra2.setForeground(new java.awt.Color(255, 255, 255));
        lblExtra2.setText("Title");

        lblExtra3.setForeground(new java.awt.Color(255, 255, 255));
        lblExtra3.setText("Username");

        lblAccountUpdated.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountUpdated.setText("Account updated");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNUID)
                            .addComponent(lblName)
                            .addComponent(lblRole)
                            .addComponent(lblEmail)
                            .addComponent(lblPhone)
                            .addComponent(lblExtra1)
                            .addComponent(lblExtra2)
                            .addComponent(lblExtra3))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldNuid)
                            .addComponent(fieldName)
                            .addComponent(fieldRole)
                            .addComponent(fieldEmail)
                            .addComponent(fieldPhone)
                            .addComponent(fieldExtra1)
                            .addComponent(fieldExtra2)
                            .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLastLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(fieldLastLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAccountUpdated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(427, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole)
                    .addComponent(lblLastLogin)
                    .addComponent(fieldLastLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(lblAccountUpdated)
                    .addComponent(fieldLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNUID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtra2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtra3))
                .addGap(133, 133, 133))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(404, 404, 404)
                    .addComponent(btnBack)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldExtra1;
    private javax.swing.JTextField fieldExtra2;
    private javax.swing.JTextField fieldLastLogin;
    private javax.swing.JTextField fieldLastUpdated;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldNuid;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldRole;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel lblAccountUpdated;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExtra1;
    private javax.swing.JLabel lblExtra2;
    private javax.swing.JLabel lblExtra3;
    private javax.swing.JLabel lblLastLogin;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
