/*
 * INFO 5100 - Application Engineering and Development
 * Assignment 3 - Profiles and Work Areas
 * Dias Mukhametrakhim, NUID 003185578
 */

package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Lists every user account with its status and times. From here the admin
 * adds a new account or opens one to update or delete it.
 *
 * @author kal bugrara (skeleton), Dias Mukhametrakhim (Assignment 3)
 */
public class ManageUserAccountsJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    UserAccount currentUser;    // the admin who is logged in


    /**
     * @param bz the business that holds every directory
     * @param current the admin who is logged in (they may not delete or disable their own account)
     * @param jp the CardLayout panel that holds the screen stack
     */
    public ManageUserAccountsJPanel(Business bz, UserAccount current, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        currentUser = current;
        initComponents();
        refreshTable();

    }

    /** Reloads the table: one row per user account. */
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblUserAccount.getModel();
        model.setRowCount(0);

        for (UserAccount ua : business.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[6];
            row[0] = ua;        // toString() shows the username; the object is read back on selection
            row[1] = ua.getAssociatedPersonProfile().getPerson().getName();
            row[2] = ua.getRole();
            row[3] = ua.getStatus();
            row[4] = ua.getLastAccessedText();
            row[5] = ua.getLastUpdatedText();
            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccount = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 58, 95));
        setLayout(null);

        btnBack.setBackground(new java.awt.Color(46, 134, 222));
        btnBack.setForeground(new java.awt.Color(244, 246, 248));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 420, 72, 23);

        btnUpdate.setBackground(new java.awt.Color(46, 134, 222));
        btnUpdate.setForeground(new java.awt.Color(244, 246, 248));
        btnUpdate.setText("View / Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(440, 420, 140, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage User Accounts");
        add(lblTitle);
        lblTitle.setBounds(30, 20, 550, 28);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPane1MousePressed(evt);
            }
        });

        tblUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Name", "Role", "Status", "Last Activity", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccount);
        if (tblUserAccount.getColumnModel().getColumnCount() > 0) {
            tblUserAccount.getColumnModel().getColumn(0).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(1).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(2).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(3).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(4).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 550, 310);

        btnAdd.setBackground(new java.awt.Color(0, 128, 0));
        btnAdd.setForeground(new java.awt.Color(244, 246, 248));
        btnAdd.setText("Add Account");
        btnAdd.setBorderPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(230, 420, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblUserAccount.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select an account first.",
                    "No account selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        UserAccount selected = (UserAccount) tblUserAccount.getValueAt(row, 0);
        AdminUserAccount detail = new AdminUserAccount(business, selected, currentUser, CardSequencePanel);
        CardSequencePanel.add("AccountDetail", detail);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MousePressed
    }//GEN-LAST:event_jScrollPane1MousePressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AdminUserAccount detail = new AdminUserAccount(business, null, currentUser, CardSequencePanel);
        CardSequencePanel.add("AccountDetail", detail);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnAddActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUserAccount;
    // End of variables declaration//GEN-END:variables

}
