/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Module.BankAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author dias
 */
public class CreateBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccountJPanel
     */
    BankAccount bankAccount;
    
    public CreateBankAccountJPanel(BankAccount ba) {
        initComponents();
        bankAccount = ba;
        
        if (bankAccount.getPerson() != null && bankAccount.getPerson().getName() != null) {
            fieldPersonName.setText(bankAccount.getPerson().getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblBranchCode = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();
        fieldAccountNumber = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        fieldBranchCode = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));

        lblTitle.setFont(new java.awt.Font("Andale Mono", 1, 24)); // NOI18N
        lblTitle.setText("Create Bank Account");

        lblPersonName.setText("Person Name");

        lblAccountNumber.setText("Account Number");

        lblBankName.setText("Bank Name");

        lblAccountType.setText("Account Type");

        lblBranchCode.setText("Branch Code");

        lblBalance.setText("Balance");

        fieldBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankNameActionPerformed(evt);
            }
        });

        fieldBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBalanceActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPersonName)
                                .addComponent(lblAccountNumber)
                                .addComponent(lblBankName)
                                .addComponent(lblAccountType)
                                .addComponent(lblBranchCode)
                                .addComponent(lblBalance))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldBalance)
                                .addComponent(fieldBranchCode)
                                .addComponent(fieldAccountType)
                                .addComponent(fieldBankName)
                                .addComponent(fieldAccountNumber)
                                .addComponent(fieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(lblTitle)
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPersonName)
                        .addComponent(fieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAccountNumber)
                        .addComponent(fieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblBankName)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAccountType)
                                .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBranchCode)
                                .addComponent(fieldBranchCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBalance)
                                .addComponent(fieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                    .addComponent(btnSave)
                    .addGap(58, 58, 58)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBalanceActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String personName = fieldPersonName.getText();
        String accountNumber = fieldAccountNumber.getText();
        String bankName = fieldBankName.getText();
        String accountType = fieldAccountType.getText();
        String branchCode = fieldBranchCode.getText();
        String balance = fieldBalance.getText();

        if(!require(personName, "Person Name")) return;
        if(!require(accountNumber, "Account Number")) return;
        if(!require(bankName, "Bank Name")) return;
        if(!require(accountType, "Account Type")) return;
        if(!require(branchCode, "Branch Code")) return;
        if(!require(balance, "Balance")) return;

        bankAccount.setPersonName(personName);
        bankAccount.setAccountNumber(accountNumber);
        bankAccount.setBankName(bankName);
        bankAccount.setAccountType(accountType);
        bankAccount.setBranchCode(branchCode);
        bankAccount.setBalance(balance);

        JOptionPane.showMessageDialog(this, "Bank Account saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        fieldPersonName.setText("");
        fieldAccountNumber.setText("");
        fieldBankName.setText("");
        fieldAccountType.setText("");
        fieldBranchCode.setText("");
        fieldBalance.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private boolean isBlank(String text){
        return text == null || text.trim().isEmpty();
    }
    
    private boolean require(String value, String label){
        if(isBlank(value)){
            JOptionPane.showMessageDialog(this,label + " is required");
            return false;
        }
        return true;
    }
    
    private void fieldBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAccountNumber;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBranchCode;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBranchCode;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
