/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Module.Address;
import Module.Person;

/**
 *
 * @author dias
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;
    Address localAddress;
    Address homeAddress;
    public MainJFrame() {
        initComponents();
        person = new Person();
        localAddress = person.getLocalAddress();
        homeAddress = person.getHomeAddress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPane = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnCrtPerson = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        btnCrtHome = new javax.swing.JButton();
        btnViewHome = new javax.swing.JButton();
        btnCrtLocal = new javax.swing.JButton();
        btnViewLocal = new javax.swing.JButton();
        btnCrtBank = new javax.swing.JButton();
        btnViewBank = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPane.setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblTitle.setText("Person Profile");

        btnCrtPerson.setText("Create Person");
        btnCrtPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrtPersonActionPerformed(evt);
            }
        });

        btnViewPerson.setText("View Person");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnCrtHome.setText("Create Home Address");
        btnCrtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrtHomeActionPerformed(evt);
            }
        });

        btnViewHome.setText("View Home Address");
        btnViewHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHomeActionPerformed(evt);
            }
        });

        btnCrtLocal.setText("Create Local Address");
        btnCrtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrtLocalActionPerformed(evt);
            }
        });

        btnViewLocal.setText("View Local Address");
        btnViewLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocalActionPerformed(evt);
            }
        });

        btnCrtBank.setText("Create Bank Account");

        btnViewBank.setText("View Bank Account");

        javax.swing.GroupLayout controlPaneLayout = new javax.swing.GroupLayout(controlPane);
        controlPane.setLayout(controlPaneLayout);
        controlPaneLayout.setHorizontalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle))
                    .addGroup(controlPaneLayout.createSequentialGroup()
                        .addGroup(controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrtPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrtHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrtBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrtLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlPaneLayout.setVerticalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle)
                .addGap(24, 24, 24)
                .addComponent(btnCrtPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPerson)
                .addGap(39, 39, 39)
                .addComponent(btnCrtHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewHome)
                .addGap(36, 36, 36)
                .addComponent(btnCrtLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewLocal)
                .addGap(45, 45, 45)
                .addComponent(btnCrtBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewBank)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPane);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrtPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrtPersonActionPerformed
        CreatePersonJPanel createPersonJPanel = new CreatePersonJPanel(person);
        splitPane.setRightComponent(createPersonJPanel);
    }//GEN-LAST:event_btnCrtPersonActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        ViewPersonJPanel viewPersonJPanel = new ViewPersonJPanel(person);
        splitPane.setRightComponent(viewPersonJPanel);
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnCrtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrtHomeActionPerformed
        CreateAddressJPanel createAddressJPanel = new CreateAddressJPanel(homeAddress, "home");
        splitPane.setRightComponent(createAddressJPanel);
    }//GEN-LAST:event_btnCrtHomeActionPerformed

    private void btnViewHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHomeActionPerformed
        ViewAddressJPanel viewAddressJPanel = new ViewAddressJPanel(homeAddress, "home");
        splitPane.setRightComponent(viewAddressJPanel);
    }//GEN-LAST:event_btnViewHomeActionPerformed

    private void btnCrtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrtLocalActionPerformed
        CreateAddressJPanel createAddressJPanel = new CreateAddressJPanel(localAddress, "local");
        splitPane.setRightComponent(createAddressJPanel);
    }//GEN-LAST:event_btnCrtLocalActionPerformed

    private void btnViewLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocalActionPerformed
        ViewAddressJPanel viewAddressJPanel = new ViewAddressJPanel(localAddress, "local");
        splitPane.setRightComponent(viewAddressJPanel);
    }//GEN-LAST:event_btnViewLocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrtBank;
    private javax.swing.JButton btnCrtHome;
    private javax.swing.JButton btnCrtLocal;
    private javax.swing.JButton btnCrtPerson;
    private javax.swing.JButton btnViewBank;
    private javax.swing.JButton btnViewHome;
    private javax.swing.JButton btnViewLocal;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JPanel controlPane;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
