/*
 * INFO 5100 - Application Engineering and Development
 * Assessment 1 - Person Profile
 * Dias Mukhametrakhim, NUID 003185578
 */
package UI;

import Module.BankAccount;

/**
 * Read-only view of a {@link Module.BankAccount}.
 *
 * <p>The fields are filled from the account and then made non-editable. The
 * balance is shown with a currency symbol in front of the stored value.</p>
 *
 * @author dias
 */
public class ViewBankAccountJPanel extends javax.swing.JPanel {

    /**
     * The bank account whose stored values this panel shows.
     */
    BankAccount bankAccount;
    /**
     * Builds the panel and immediately shows the account's stored values.
     *
     * @param ba the bank account to display
     */
    public ViewBankAccountJPanel(BankAccount ba) {
        initComponents();
        bankAccount = ba;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblBranchCode = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();
        fieldAccountNumber = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        fieldBranchCode = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 255));

        lblTitle.setFont(new java.awt.Font("Andale Mono", 1, 24)); // NOI18N
        lblTitle.setText("View Bank Account");

        lblPersonName.setText("Person Name");

        lblAccountNumber.setText("Account Number");

        lblBankName.setText("Bank Name");

        lblAccountType.setText("Account Type");

        lblBranchCode.setText("Branch Code");

        lblBalance.setText("Balance");

        fieldBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBankNameActionPerformed(evt);
            }
        });

        fieldBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBalanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPersonName)
                                .addComponent(lblAccountNumber)
                                .addComponent(lblBankName)
                                .addComponent(lblAccountType)
                                .addComponent(lblBranchCode)
                                .addComponent(lblBalance))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldBalance)
                                .addComponent(fieldBranchCode)
                                .addComponent(fieldAccountType)
                                .addComponent(fieldBankName)
                                .addComponent(fieldAccountNumber)
                                .addComponent(fieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(97, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(lblTitle)
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPersonName)
                        .addComponent(fieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAccountNumber)
                        .addComponent(fieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblBankName)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAccountType)
                                .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBranchCode)
                                .addComponent(fieldBranchCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBalance)
                                .addComponent(fieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(145, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBankNameActionPerformed

    private void fieldBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBalanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAccountNumber;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBranchCode;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBranchCode;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * Copies the account attributes into the fields and locks them.
     *
     * <p>The balance is shown with a currency symbol in front of the stored
     * text; the stored attribute itself is unchanged.</p>
     */
    private void display() {
        fieldPersonName.setText(bankAccount.getPersonName());
        fieldAccountNumber.setText(bankAccount.getAccountNumber());
        fieldBankName.setText(bankAccount.getBankName());
        fieldAccountType.setText(bankAccount.getAccountType());
        fieldBranchCode.setText(bankAccount.getBranchCode());
        fieldBalance.setText("$" +bankAccount.getBalance());
        
        fieldPersonName.setEditable(false);
        fieldAccountNumber.setEditable(false);
        fieldBankName.setEditable(false);
        fieldAccountType.setEditable(false);
        fieldBranchCode.setEditable(false);
        fieldBalance.setEditable(false);

    }
}
