package UI;

import Model.Business;
import Model.ConfigureABusiness;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dias
 */
public class MainJFrame extends javax.swing.JFrame {

    /** The whole coffee shop model, pre-populated with demo data at start-up. */
    
    private Business business;
    
    public MainJFrame() {
        initComponents();
        business = ConfigureABusiness.initialize();
        setTitle(business.getName() + " - Point of Sale");
        setLocationRelativeTo(null);
        showWorkArea("ListOrdersJPanel", new ListOrdersJPanel(userProcessContainer, business));
    }
    
    /**
     * Clears the card stack and shows one work panel chosen in the navigation.
     *
     * <p>removeAll() comes first so that clicking the same button again does
     * not keep piling copies of the panel onto the stack.</p>
     */
    private void showWorkArea(String name, JPanel panel) {
        userProcessContainer.removeAll();
        userProcessContainer.add(name, panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        navPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnManageProducts = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        btnSearchCustomers = new javax.swing.JButton();
        btnListOrders = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(200);
        splitPane.setDividerSize(4);
        splitPane.setPreferredSize(new java.awt.Dimension(1100, 650));

        navPanel.setBackground(new java.awt.Color(62, 39, 35));
        navPanel.setMinimumSize(new java.awt.Dimension(200, 0));
        navPanel.setPreferredSize(new java.awt.Dimension(200, 650));

        lblTitle.setFont(new java.awt.Font("American Typewriter", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Сoffe POS");

        btnManageProducts.setText("Manage Products");
        btnManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductsActionPerformed(evt);
            }
        });

        btnNewOrder.setText("New Customer Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnSearchCustomers.setText("Search Customers");
        btnSearchCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomersActionPerformed(evt);
            }
        });

        btnListOrders.setText("\tList Orders");
        btnListOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblTitle))
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNewOrder)
                            .addComponent(btnManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addComponent(btnManageProducts)
                .addGap(18, 18, 18)
                .addComponent(btnNewOrder)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCustomers)
                .addGap(18, 18, 18)
                .addComponent(btnListOrders)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(navPanel);

        userProcessContainer.setBackground(new java.awt.Color(245, 241, 235));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(900, 650));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductsActionPerformed
        showWorkArea("ManageProductsJPanel", new ManageProductsJPanel(business));
    }//GEN-LAST:event_btnManageProductsActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        showWorkArea("AddCustomerOrderJPanel", new AddCustomerOrderJPanel(business));
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnSearchCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomersActionPerformed
        showWorkArea("SearchCustomersJPanel", new SearchCustomersJPanel(userProcessContainer, business));
    }//GEN-LAST:event_btnSearchCustomersActionPerformed

    private void btnListOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListOrdersActionPerformed
        showWorkArea("ListOrdersJPanel", new ListOrdersJPanel(userProcessContainer, business));
    }//GEN-LAST:event_btnListOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListOrders;
    private javax.swing.JButton btnManageProducts;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnSearchCustomers;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel navPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
