/*
 * INFO 5100 - Application Engineering and Development
 * Assignment 3 - Profiles and Work Areas
 * Dias Mukhametrakhim, NUID 003185578
 */
package UserInterface.WorkAreas.AdminRole.ManageFacultyWorkResp;

import Business.Business;
import Business.Profiles.FacultyProfile;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Lists every faculty member. From here the admin adds a faculty member
 * (with a login) or opens one to update or delete them.
 *
 * @author Dias Mukhametrakhim
 */
public class ManageFacultyJPanel extends javax.swing.JPanel {
    JPanel CardSequencePanel;
    Business business;


    public ManageFacultyJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();
    }
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();
        model.setRowCount(0);

        for (FacultyProfile fp : business.getFacultyDirectory().getFacultyList()) {
            UserAccount ua = business.getUserAccountDirectory().findByProfile(fp);
            Object[] row = new Object[6];
            row[0] = fp.getPerson().getPersonId();     // the NUID finds the faculty member again on selection
            row[1] = fp.getPerson().getName();
            row[2] = fp.getDepartment();
            row[3] = fp.getTitle();
            row[4] = fp.getPerson().getEmail();
            row[5] = ua == null ? "No account" : ua.getUserLoginName();
            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnRegister = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 58, 95));
        setLayout(null);

        btnBack.setBackground(new java.awt.Color(46, 134, 222));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 420, 72, 23);

        btnUpdate.setBackground(new java.awt.Color(46, 134, 222));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("View / Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(400, 420, 230, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Faculty");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUID", "Name", "Department", "Title", "Email", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFaculty.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblFaculty);
        if (tblFaculty.getColumnModel().getColumnCount() > 0) {
            tblFaculty.getColumnModel().getColumn(0).setResizable(false);
            tblFaculty.getColumnModel().getColumn(2).setResizable(false);
            tblFaculty.getColumnModel().getColumn(3).setResizable(false);
            tblFaculty.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 610, 270);

        btnRegister.setBackground(new java.awt.Color(0, 128, 0));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Add Faculty");
        btnRegister.setBorderPainted(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister);
        btnRegister.setBounds(190, 420, 150, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblFaculty.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a faculty member first.",
                    "No faculty member selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String nuid = (String) tblFaculty.getValueAt(row, 0);
        FacultyProfile faculty = business.getFacultyDirectory().findFaculty(nuid);
        AdministerFacultyJPanel detail = new AdministerFacultyJPanel(business, faculty, CardSequencePanel);
        CardSequencePanel.add("FacultyDetail", detail);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        AdministerFacultyJPanel detail = new AdministerFacultyJPanel(business, null, CardSequencePanel);
        CardSequencePanel.add("FacultyDetail", detail);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblFaculty;
    // End of variables declaration//GEN-END:variables

}
